### ISSUE TITLE
Inventory plugins with errors emit obtuse error messages

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/bolt#1306]
## Describe the Bug
Now that Inventory V2 accepts plugins, bolt will be executing arbitrary code which means that data from the plugins should probably be check as valid e.g. During a target lookup, the plugin can return a nil value which displays the following obtuse error message

```
Traceback (most recent call last):
        18: from C:/Source/ad_inventory/.bundle/windows/ruby/2.5.0/bin/bolt:23:in `<main>'
        17: from C:/Source/ad_inventory/.bundle/windows/ruby/2.5.0/bin/bolt:23:in `load'
        16: from C:/Source/ad_inventory/.bundle/windows/ruby/2.5.0/gems/bolt-1.33.0/exe/bolt:9:in `<top (required)>'
        15: from C:/Source/ad_inventory/.bundle/windows/ruby/2.5.0/gems/bolt-1.33.0/lib/bolt/cli.rb:134:in `parse'
        14: from C:/Source/ad_inventory/.bundle/windows/ruby/2.5.0/gems/bolt-1.33.0/lib/bolt/cli.rb:165:in `update_targets'
        13: from C:/Source/ad_inventory/.bundle/windows/ruby/2.5.0/gems/bolt-1.33.0/lib/bolt/cli.rb:53:in `inventory'
        12: from C:/Source/ad_inventory/.bundle/windows/ruby/2.5.0/gems/bolt-1.33.0/lib/bolt/inventory.rb:57:in `from_config'
        11: from C:/Source/ad_inventory/.bundle/windows/ruby/2.5.0/gems/bolt-1.33.0/lib/bolt/inventory.rb:68:in `create_version'
        10: from C:/Source/ad_inventory/.bundle/windows/ruby/2.5.0/gems/bolt-1.33.0/lib/bolt/inventory.rb:68:in `new'
         9: from C:/Source/ad_inventory/.bundle/windows/ruby/2.5.0/gems/bolt-1.33.0/lib/bolt/inventory/inventory2.rb:21:in `initialize'
         8: from C:/Source/ad_inventory/.bundle/windows/ruby/2.5.0/gems/bolt-1.33.0/lib/bolt/inventory/inventory2.rb:21:in `new'
         7: from C:/Source/ad_inventory/.bundle/windows/ruby/2.5.0/gems/bolt-1.33.0/lib/bolt/inventory/group2.rb:85:in `initialize'
         6: from C:/Source/ad_inventory/.bundle/windows/ruby/2.5.0/gems/bolt-1.33.0/lib/bolt/inventory/group2.rb:85:in `map'
         5: from C:/Source/ad_inventory/.bundle/windows/ruby/2.5.0/gems/bolt-1.33.0/lib/bolt/inventory/group2.rb:85:in `block in initialize'
         4: from C:/Source/ad_inventory/.bundle/windows/ruby/2.5.0/gems/bolt-1.33.0/lib/bolt/inventory/group2.rb:85:in `new'
         3: from C:/Source/ad_inventory/.bundle/windows/ruby/2.5.0/gems/bolt-1.33.0/lib/bolt/inventory/group2.rb:67:in `initialize'
         2: from C:/Source/ad_inventory/.bundle/windows/ruby/2.5.0/gems/bolt-1.33.0/lib/bolt/inventory/group2.rb:67:in `each'
         1: from C:/Source/ad_inventory/.bundle/windows/ruby/2.5.0/gems/bolt-1.33.0/lib/bolt/inventory/group2.rb:76:in `block in initialize'
C:/Source/ad_inventory/.bundle/windows/ruby/2.5.0/gems/bolt-1.33.0/lib/bolt/inventory/group2.rb:233:in `lookup_targets': undefined method `each' for nil:NilClass (NoMethodError)
```

This could also be thrown if the plugin returns a hash or integer

## Expected Behavior
Bolt should validate the object being returned from the plugin and raise a meaningful error to the user.  In the example above:

```
The plugin '<plugin name>' returned a nil value but bolt expected an array of targets
```

...or something along those lines.  To give the user a better idea of what's gone wrong.

https://github.com/puppetlabs/bolt/blob/57b0cbe17a/lib/bolt/inventory/group2.rb#L226-L233

## Steps to Reproduce
Create an inventory plugin that returns a nil value when called

## Environment
 - Version: Bolt 1.33.0 (Gem)
 - Platform Windows x64 1903

## Additional Context
This is very useful both when developing plugins and running them in production.  Obtuse error messages make it difficult for the user to determine where exactly the failure is, and then who to contact.  In the example above, the user would probably assume it's a bug in Bolt, but it's really a bug in the plugin.

**Comment by lucywyman** [comment]
We should check that `resolve_reference` returns an array for targets (when looking up targets) - Nick will do this as part of the work for #1147

**Comment by donoghuc** [comment]
This appears to have been resolved with https://github.com/puppetlabs/bolt/pull/1340 . 
With the folloing inventory:
```yaml
version: 2
targets:
  - _plugin: task
    task: test::nil_target
```
and with the `nil_target` implementation:
```ruby
#!/usr/bin/env ruby
require 'json'
puts JSON.dump({value: nil})
```
The following message is displayed:
```
cas@cas-ThinkPad-T460p:~/working_dir/bolt$ bolt command run whoami -t all
Node entry must be a String or Hash, not NilClass for group at ["all"]
```
Similarly with the `test::nil_target` implementation:
```ruby
#!/usr/bin/env ruby
return nil
```
the following message is displayed:
```
cas@cas-ThinkPad-T460p:~/working_dir/bolt$ bolt command run whoami -t all
Error executing plugin task from resolve_reference in all: Task result did not return 'value': {"_output"=>""}
```

**Comment by donoghuc** [comment]
Fixed with https://github.com/puppetlabs/bolt/pull/1340
