### ISSUE TITLE
gssapi fails on debian buster

### ISSUE THREAD

**Issue by faxm0dem** [puppetlabs/bolt#1529]
## failure to use gssapi authentication

GSSAPI auth doesn't seem to work:

```
Authentication method 'gssapi-with-mic' (Kerberos) is not available.
```

## Expected Behavior

bolt should support all ssh auth methods

## Steps to Reproduce

1. configure ssh config for using gssapi
2. run any bolt command on host

## Environment
 - Version 1.44.0-1buster
 - Platform Debian Buster

## Full stacktrace

```
<Gem::ConflictError> Unable to activate net-ssh-krb-0.4.0, because gssapi-1.3.0 conflicts with gssapi (~> 1.2.0)
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems/specification.rb:2325:in `raise_if_conflicts'
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems/specification.rb:1438:in `activate'
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems.rb:224:in `rescue in try_activate'
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems.rb:217:in `try_activate'
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/transport/ssh.rb:65:in `initialize'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/executor.rb:35:in `new'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/executor.rb:35:in `block (2 levels) in initialize'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/delay.rb:87:in `block in value'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `block in synchronize'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/delay.rb:83:in `value'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/delay.rb:137:in `wait'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/concern/obligation.rb:87:in `wait!'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/executor.rb:57:in `transport'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/executor.rb:90:in `block in queue_execute'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/executor.rb:89:in `each'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/executor.rb:89:in `flat_map'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/executor.rb:89:in `queue_execute'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/executor.rb:145:in `batch_execute'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/executor.rb:259:in `block in run_task'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/executor.rb:153:in `log_action'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/executor.rb:255:in `run_task'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/bolt-modules/boltlib/lib/puppet/functions/run_task.rb:127:in `run_task_with_description'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pops/functions/dispatch.rb:60:in `invoke'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pops/functions/dispatcher.rb:43:in `block in dispatch'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pops/functions/dispatcher.rb:42:in `catch'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pops/functions/dispatcher.rb:42:in `dispatch'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pops/functions/function.rb:46:in `block in call'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pops/functions/function.rb:45:in `catch'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pops/functions/function.rb:45:in `call'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pops/evaluator/runtime3_support.rb:283:in `block in external_call_function'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/util/profiler/around_profiler.rb:58:in `profile'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/util/profiler.rb:51:in `profile'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pops/evaluator/runtime3_support.rb:282:in `external_call_function'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pal/compiler.rb:29:in `call_function'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/pal.rb:427:in `block in run_task'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/pal.rb:199:in `block (2 levels) in in_task_compiler'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/pal.rb:142:in `block (3 levels) in in_bolt_compiler'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/context.rb:62:in `override'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet.rb:274:in `override'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/pal.rb:141:in `block (2 levels) in in_bolt_compiler'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pal/pal_impl.rb:468:in `block (3 levels) in main'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/parser/script_compiler.rb:47:in `block in compile'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/context.rb:62:in `override'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet.rb:274:in `override'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/parser/script_compiler.rb:42:in `compile'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pal/pal_impl.rb:465:in `block (2 levels) in main'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/context.rb:62:in `override'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet.rb:274:in `override'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pal/pal_impl.rb:464:in `block in main'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/context.rb:62:in `override'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet.rb:274:in `override'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pal/pal_impl.rb:418:in `main'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pal/pal_impl.rb:92:in `with_script_compiler'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/pal.rb:137:in `block in in_bolt_compiler'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pal/pal_impl.rb:330:in `block in in_environment_context'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/context.rb:62:in `override'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet.rb:274:in `override'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pal/pal_impl.rb:322:in `in_environment_context'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pal/pal_impl.rb:224:in `in_tmp_environment'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/pal.rb:136:in `in_bolt_compiler'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/pal.rb:198:in `block in in_task_compiler'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/context.rb:62:in `override'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet.rb:274:in `override'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/pal.rb:180:in `with_bolt_executor'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/pal.rb:197:in `in_task_compiler'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/pal.rb:425:in `run_task'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/cli.rb:416:in `block in execute'
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/cli.rb:402:in `execute'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/exe/bolt:10:in `<top (required)>'
        /opt/puppetlabs/bolt/bin/bolt:23:in `load'
        /opt/puppetlabs/bolt/bin/bolt:23:in `<main>'
        --- Caused by ---
        <Gem::ConflictError> Unable to activate net-ssh-krb-0.4.0, because gssapi-1.3.0 conflicts with gssapi (~> 1.2.0)
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems/specification.rb:2325:in `raise_if_conflicts'
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems/specification.rb:1438:in `activate'
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems.rb:218:in `try_activate'
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/transport/ssh.rb:65:in `initialize'
        --- Caused by ---
        <LoadError> cannot load such file -- net/ssh/krb
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/transport/ssh.rb:65:in `initialize'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/executor.rb:35:in `new'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/executor.rb:35:in `block (2 levels) in initialize'
```

**Comment by lucywyman** [comment]
Hi @faxm0dem - this is a known issue (https://puppet.com/docs/bolt/latest/bolt_known_issues.html#limited-kerberos-support). We can't formally recommend installing the net-ssh-krb gem, but if you [install](https://puppet.com/docs/bolt/latest/bolt_installing.html#install-gems-with-bolt-packages) the [net-ssh-krb gem](https://rubygems.org/gems/net-ssh-krb) into the bolt environment with `/opt/puppetlabs/bolt/bin/gem install --user-install <gem>` you should be able to authenticate with kerberos.

**Comment by faxm0dem** [comment]
Thanks for the clarification. However, I did install the gem, and I improved the error message from the import in bolt. Here's an exerpt from the above output:

```
Unable to activate net-ssh-krb-0.4.0, because gssapi-1.3.0 conflicts with gssapi (~> 1.2.0)
```

**Comment by donoghuc** [comment]
We started shipping gssapi 1.3.0 in June https://github.com/puppetlabs/puppet-runtime/commit/4117569967db9a7d93427501329bfd7bcd0f9070#diff-f95c9606aff1f7dd5945188b3fd64298L2-L6 Looks like net-ssh-rkb is restricted to the 1.2.x series. So that "informal" solution will no longer work.

**Comment by adreyer** [comment]
Yeah I think someone will have to fork the kerberos gem to update that dependency.

**Comment by faxm0dem** [comment]
@adreyer thanks for stepping up, highly appreciated ;-)

**Comment by faxm0dem** [comment]
woo-hoo there seems to be a new version available https://rubygems.org/gems/net-ssh-krb

**Comment by faxm0dem** [comment]
it seems 59d3f66629f1a4b8bc6fe4a4b9a52812446665d3 removed the code that activated gssapi authentication. @lucywyman was this a mistake?

**Comment by lucywyman** [comment]
No, we previously could not ship with the gem so had to try to load it and fail if it wasn't in bolt's gem environment. That allowed users to manually add the gem if they liked, and see the warning if they tried to use gssapi without it. The net-ssh gem is what uses net-ssh-krb, so now that we know it's available in bolt's gem env we don't have to try to load it to make sure it's there.

**Comment by faxm0dem** [comment]
the problem is that gssapi auth doesn't work without those lines:
```
+        begin
+          require 'net/ssh/krb'
+        rescue LoadError
+          logger.debug("Authentication method 'gssapi-with-mic' (Kerberos) is not available.")
+        end
```

**Comment by donoghuc** [comment]
We still have to require the library, we just dont need to rescue a LoadError bc the gemspec ensures the gem is available.
