### ISSUE TITLE
Human outputter does not print plan result for wait_until_available correctly

### ISSUE THREAD

**Issue by donoghuc** [puppetlabs/bolt#1718]
## Describe the Bug
The result object created from wait_until_available does not have an `action`. The human outputter wants to print the action and fails when it attempts to capitalize it when printing a result. 

## Expected Behavior
Maybe wait_until_available should have an action? 

## Steps to Reproduce
```
plan test(){
    return wait_until_available('localhost')
}
```
```
NoMethodError: undefined method `capitalize' for nil:NilClass
  /home/cas/working_dir/bolt/lib/bolt/outputter/human.rb:101:in `print_result'
  /home/cas/working_dir/bolt/lib/bolt/outputter/human.rb:362:in `block in print_result_set'
  /home/cas/working_dir/bolt/lib/bolt/result_set.rb:41:in `block in each'
  /home/cas/working_dir/bolt/lib/bolt/result_set.rb:41:in `each'
  /home/cas/working_dir/bolt/lib/bolt/result_set.rb:41:in `each'
  /home/cas/working_dir/bolt/lib/bolt/outputter/human.rb:362:in `print_result_set'
  /home/cas/working_dir/bolt/lib/bolt/outputter/human.rb:355:in `print_plan_result'
  /home/cas/working_dir/bolt/lib/bolt/cli.rb:524:in `run_plan'
  /home/cas/working_dir/bolt/lib/bolt/cli.rb:373:in `execute'
  /home/cas/working_dir/bolt/exe/bolt:10:in `<top (required)>'
  /home/cas/working_dir/bolt/vendor/bundle/ruby/2.5.0/bin/bolt:23:in `load'
  /home/cas/working_dir/bolt/vendor/bundle/ruby/2.5.0/bin/bolt:23:in `<top (required)>'
```

**Comment by nmaludy** [comment]
This can be closed, it is fixed in 2.5.0 as part of #1726
