### ISSUE TITLE
Bolt throws exception if target returns "null" on a remote task

### ISSUE THREAD

**Issue by nmaludy** [puppetlabs/bolt#1724]
## Describe the Bug
When running a plan that calls `run_task()` on a `remote` task, then the task itself returns `null`, then Bolt throws an exception when trying to print out the results:

Example target result:
```
{"target":"hostname.domain.tld","action":null,"object":null,"status":"success","value":{"_output":""}}
```

```
Traceback (most recent call last):
        11: from /opt/puppetlabs/bolt/bin/bolt:23:in `<main>'
        10: from /opt/puppetlabs/bolt/bin/bolt:23:in `load'
         9: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/exe/bolt:10:in `<top (required)>'
         8: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/cli.rb:373:in `execute'
         7: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/cli.rb:524:in `run_plan'
         6: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/outputter/human.rb:355:in `print_plan_result'
         5: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/outputter/human.rb:362:in `print_result_set'
         4: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/result_set.rb:41:in `each'
         3: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/result_set.rb:41:in `each'
         2: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/result_set.rb:41:in `block in each'
         1: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/outputter/human.rb:362:in `block in print_result_set'
/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/outputter/human.rb:101:in `print_result': undefined method `capitalize' for nil:NilClass (NoMethodError)
```

If i run the task itself, it does not error.

## Expected Behavior
No exception is thrown when running from a plan.

## Steps to Reproduce
tasks/plan_exception.rb
```ruby
#!/usr/bin/env ruby
require_relative '../../ruby_task_helper/files/task_helper.rb'

# Bolt task for enabling/disabling monitoring alerts in SolarWinds
class PlanExceptionTask < TaskHelper
  def task(**kwargs)
    nil
  end
end

PlanExceptionTask.run if $PROGRAM_NAME == __FILE__
```

tasks/plan_exception.json
```json
{
  "description": "Returns null",
  "remote": true,
  "files": [
    "ruby_task_helper/files/task_helper.rb"
  ],
  "parameters": {}
}
```

plans/plan_exception.pp
```
plan mymodule::plan_exception () {
  return(run_task('mymodule::plan_exception', 'remote_target'))
}
```

inventory.yaml
```
---
version: 2
groups:
  - name: remote_target
    config:
      transport: remote
      remote: {}
    targets:
      - hostname.domain.tld
```

Run the plan on the CLI
```
$ bolt plan run mymodule::plan_exception --targets remote_target
Starting: plan mymodule::plan_exception
Starting: plan mymodule::plan_exception
Starting: task mymodule::plan_exception on hostname.domain.tld
Finished: task mymodule::plan_exception with 0 failures in 0.09 sec
Finished: plan mymodule::plan_exception in 0.1 sec
Finished: plan mymodule::plan_exception in 0.1 sec
Finished on hostname.domain.tld:
Traceback (most recent call last):
        11: from /opt/puppetlabs/bolt/bin/bolt:23:in `<main>'
        10: from /opt/puppetlabs/bolt/bin/bolt:23:in `load'
         9: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/exe/bolt:10:in `<top (required)>'
         8: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/cli.rb:373:in `execute'
         7: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/cli.rb:524:in `run_plan'
         6: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/outputter/human.rb:355:in `print_plan_result'
         5: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/outputter/human.rb:362:in `print_result_set'
         4: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/result_set.rb:41:in `each'
         3: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/result_set.rb:41:in `each'
         2: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/result_set.rb:41:in `block in each'
         1: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/outputter/human.rb:362:in `block in print_result_set'
/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/outputter/human.rb:101:in `print_result': undefined method `capitalize' for nil:NilClass (NoMethodError)
```

## Environment
 - Version: `2.3.0`
 - Platform: `CentOS 7`

**Comment by donoghuc** [comment]
This is very similar to https://github.com/puppetlabs/bolt/issues/1718 . There is no action assigned to result https://github.com/puppetlabs/bolt/blob/master/lib/bolt/transport/remote.rb#L37

**Comment by nmaludy** [comment]
Decision from conversation on Slack:
- Make Result action default to 'action'? So you get “Action completed successfully with no result”
- Fix places we've found where 'action' wasn't set.
