### ISSUE TITLE
cannot load such file -- addressable

### ISSUE THREAD

**Issue by cygnus8595** [puppetlabs/bolt#178]
I was setting up bolt and I got this error:

```
C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require': cannot load such file -- addressable (LoadError)
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bolt-0.9.0/lib/bolt/node_uri.rb:1:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bolt-0.9.0/lib/bolt/node.rb:2:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bolt-0.9.0/lib/bolt.rb:3:in `<module:Bolt>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bolt-0.9.0/lib/bolt.rb:1:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bolt-0.9.0/exe/bolt:3:in `<top (required)>'
        from C:/Ruby23-x64/bin/bolt:22:in `load'
        from C:/Ruby23-x64/bin/bolt:22:in `<main>'
```
Looking up the documentation for the addressable gem, I found this: http://www.rubydoc.info/gems/addressable

I changed the top line of node_uri.rb from `require 'addressable'` to `require 'addressable/uri'` and then everything worked.

I don't know if anyone else had this issue, but maybe someone with more access than me can update that if necessary. :)

**Comment by joshcooper** [comment]
The `addressable` gem made it possible to require the top-level module in https://github.com/sporkmonger/addressable/commit/0475980bb943dfcac2141c8f40b45ea2e6e5f76f. It also looks like bolt doesn't require a minimum version of `addressable` so you could run into this error if you already had an older version of addressable installed. We should either `require 'addressable/uri'` and/or require at least addressable >= 2.4.0.
