### ISSUE TITLE
bolt plan apply fails when puppet agent path is not in ${env:programfiles}

### ISSUE THREAD

**Issue by rogfut** [puppetlabs/bolt#1967]
## Describe the Bug
Windows targets with Puppet Enterprise agents installed at a path other than ${env:programfiles} fail to run bolt plan apply with error:
```
Failed on server01:
  Puppet is not installed on the target in $env:ProgramFiles, please install it to enable 'apply'
```

It seems like bolt plan apply is assuming a puppet agent path of ${env:programfiles}, despite my PE agent installation path being available at RememberedInstallDir64 in 'HKLM:\SOFTWARE\Puppet Labs\Puppet':

```
PS C:\Windows\system32> $rootPath = 'HKLM:\SOFTWARE\Puppet Labs\Puppet'
PS C:\Windows\system32> Get-ItemProperty -Path $rootPath -ErrorAction SilentlyContinue


RememberedInstallDir64 : D:\Program Files\Puppet Labs\Puppet\
(default)              : 0
RememberedInstallDir   :
PSPath                 : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Puppet Labs\Puppet
PSParentPath           : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Puppet Labs
PSChildName            : Puppet
PSDrive                : HKLM
PSProvider             : Microsoft.PowerShell.Core\Registry
```

## Expected Behavior
bolt plan's apply should be able to detect the puppet installation path from RememberedInstallDir or RememberedInstallDir64 in registry key ```HKLM:\SOFTWARE\Puppet Labs\Puppet``` instead of assuming ${env:ProgramFiles}

## Steps to Reproduce
1. Install the PE agent on a Windows target at any path other than ${env:programfiles}\Puppet Labs
2. Create a simple bolt plan
```
plan my_module::test(
  TargetSpec $targets
){
  apply($targets) {
    File { 'D:\\Temp':
      ensure => present
    }
  }
}
```
3. Apply the Bolt plan to the windows target
```
bolt plan apply my_module::test --targets server01 --transport winrm
```

4. Observe the failure
```
Starting: plan my_module::test
Starting: apply catalog on server01
Finished: apply catalog with 1 failure in 32.33 sec
Finished: plan bootstrap_puppet::test in 32.34 sec
Failed on server01:
  Puppet is not installed on the target in $env:ProgramFiles, please install it to enable 'apply'
Failed on 1 target: server01
Ran on 1 target
``` 

## Environment
Client:
Bolt Version 2.16.0
Windows Version 
PowerShell 5.1 build 17763 revision 1007

Windows Target:
Windows Version 10.0.14393
Powershell 5.1 build 14393 revision 3471
Transport used: WinRM

## Additional Context
Notice that I left out ```apply_prep``` from my bolt plan manifest code.  I left it out because I know that puppet agent is installed on the target and because I was hitting an issue with apply_prep as well as ```bolt apply``` from the command line where ```apply_helpers::custom_facts``` fails because it can't find ruby.exe.  It looks like the reason it can't find ruby.exe is because it expects it at ```${ENV:ProgramFiles}\Puppet Labs\Puppet\sys\ruby\bin\```

I was planning on logging a separate bug for the ```bolt apply``` issue when ran outside of a bolt plan.

**Comment by jpogran** [comment]
Tested this on windows2012R2 and it correctly fails to find puppet if its not there and emits the correct message, and when puppet is installed to a non default location it finds puppet on the E Drive.

```
 bundle exec bolt plan run  'boltfoobar::test' --targets 'winrm://172.28.15.21' -u ***** -p ***** --no-ssl --no-ssl-verify
[DEPRECATION] Struct layout is already defined for class Windows::ServiceStructs::SERVICE_STATUS_PROCESS. Redefinition as in C:/Users/james/src/puppetlabs/bolt/.bundle/gems/ruby/2.5.0/gems/win32-service-0.8.8/lib/win32/windows/structs.rb:67:in `<class:SERVICE_STATUS_PROCESS>' will be disallowed in ffi-2.0.
Starting: plan boltfoobar::test
Starting: apply catalog on winrm://172.28.15.21
winrm://172.28.15.21: [DEPRECATION] Struct layout is already defined for class Windows::ServiceStructs::SERVICE_STATUS_PROCESS. Redefinition as in C:/Users/james/src/puppetlabs/bolt/.bundle/gems/ruby/2.5.0/gems/win32-service-0.8.8/lib/win32/windows/structs.rb:67:in `<class:SERVICE_STATUS_PROCESS>' will be disallowed in ffi-2.0.
Finished: apply catalog with 1 failure in 16.73 sec
Finished: plan boltfoobar::test in 16.73 sec
Failed on winrm://172.28.15.21:
  Puppet was not found on the target or in $env:ProgramFiles, please install it to enable 'apply'
Failed on 1 target: winrm://172.28.15.21
Ran on 1 target
 bundle exec bolt plan run  'boltfoobar::test' --targets 'winrm://172.28.15.21' -u ***** -p ***** --no-ssl --no-ssl-verify
[DEPRECATION] Struct layout is already defined for class Windows::ServiceStructs::SERVICE_STATUS_PROCESS. Redefinition as in C:/Users/james/src/puppetlabs/bolt/.bundle/gems/ruby/2.5.0/gems/win32-service-0.8.8/lib/win32/windows/structs.rb:67:in `<class:SERVICE_STATUS_PROCESS>' will be disallowed in ffi-2.0.
Starting: plan boltfoobar::test
Starting: apply catalog on winrm://172.28.15.21
winrm://172.28.15.21: [DEPRECATION] Struct layout is already defined for class Windows::ServiceStructs::SERVICE_STATUS_PROCESS. Redefinition as in C:/Users/james/src/puppetlabs/bolt/.bundle/gems/ruby/2.5.0/gems/win32-service-0.8.8/lib/win32/windows/structs.rb:67:in `<class:SERVICE_STATUS_PROCESS>' will be disallowed in ffi-2.0.
Finished: apply catalog with 0 failures in 19.85 sec
Finished: plan boltfoobar::test in 19.85 sec
Plan completed successfully with no result

```
