### ISSUE TITLE
Bolt hangs/crashes when loosing winrm service

### ISSUE THREAD

**Issue by bishopbm1** [puppetlabs/bolt#1982]
## Describe the Bug
When running commands on windows if the WinRM Service gets restarted/flaps/or goes down for any reason the following error occurs and bolt just crashes and hangs until user input to exit out of the command.

Error:
```
# bolt task run --modulepath /opt/encore/puppet/ --targets winrm://1.2.3.4:5986 --user testuser --password testpassword --no-ssl-verify service action='restart' name='WinRM' force='true'
Fact file /etc/facter/facts.d/encore.json was parsed but returned an empty data set
Started on winrm://1.2.3.4:5986...
#<Thread:0x00007f6c68993870@/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:471 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
  14: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
  13: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.16.0/lib/bolt/transport/winrm/connection.rb:114:in `block in execute'
  12: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/shells/base.rb:79:in `run'
  11: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/shells/base.rb:131:in `with_command_shell'
  10: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/shells/base.rb:80:in `block in run'
   9: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/psrp/receive_response_reader.rb:58:in `read_output'
   8: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/wsmv/receive_response_reader.rb:73:in `with_output'
   7: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/psrp/receive_response_reader.rb:59:in `block in read_output'
   6: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/psrp/receive_response_reader.rb:39:in `read_message'
   5: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/wsmv/receive_response_reader.rb:61:in `read_response'
   4: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/wsmv/receive_response_reader.rb:93:in `send_get_output_message'
   3: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/http/transport.rb:186:in `send_request'
   2: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/http/response_handler.rb:34:in `parse_to_xml'
   1: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/http/response_handler.rb:52:in `raise_if_error'
/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/http/response_handler.rb:73:in `raise_if_wsman_fault': [WSMAN ERROR CODE: 995]: <f:WSManFault Code='995' Machine='1.2.3.4' xmlns:f='http://schemas.microsoft.com/wbem/wsman/1/wsmanfault'><f:Message>The I/O operation has been aborted because of either a thread exit or an application request. </f:Message></f:WSManFault> (WinRM::WinRMWSManFault)
```

To add some context we are attempting to use bolt to update a fresh install of windows and some of the updates cause the WinRM service to get restarted or flap momentarily and then the above error occurs. The problem is that bolt crashes and hangs until the user exits the bolt run (ctrl-c). If this were to error within bolt then we could use `_catch_errors` and do a retry within the plan to handle the error and continue patching. If the service is restarted when a command is not actively running then the error is handled fine with a 'failed to connect message' it only occurs when the service restarts in the middle of an action. 

## Expected Behavior
An exception is raise that can be handled with `_catch_errors` or exit gracefully within bolt.

## Steps to Reproduce
Run any plan and when the a command is running restart the WinRM service within windows.

Patching Plan:
```
bolt plan run patching --modulepath /opt/encore/puppet/ --targets winrm://1.2.3.4:5986 --user testuser --password testpassword --no-ssl-verify --connect-timeout 120
Fact file /etc/facter/facts.d/encore.json was parsed but returned an empty data set
Starting: plan patching
Starting: plan patching::check_puppet
Starting: task puppet_agent::version on winrm://1.2.3.4:5986
Finished: task puppet_agent::version with 0 failures in 3.37 sec
Starting: plan facts
Starting: task facts on winrm://1.2.3.4:5986
Finished: task facts with 0 failures in 3.72 sec
Finished: plan facts in 3.74 sec
Finished: plan patching::check_puppet in 7.16 sec
Starting: plan patching::ordered_groups
Groups = []
Group '' targets = [winrm://1.2.3.4:5986]
Finished: plan patching::ordered_groups in 0.06 sec
Starting: task patching::cache_update on winrm://1.2.3.4:5986
Finished: task patching::cache_update with 0 failures in 3.85 sec
Starting: plan patching::available_updates
Starting: task patching::available_updates on winrm://1.2.3.4:5986
#<Thread:0x000000000464baa0@/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:471 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
  14: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
  13: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.16.0/lib/bolt/transport/winrm/connection.rb:114:in `block in execute'
  12: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/shells/base.rb:79:in `run'
  11: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/shells/base.rb:131:in `with_command_shell'
  10: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/shells/base.rb:80:in `block in run'
   9: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/psrp/receive_response_reader.rb:58:in `read_output'
   8: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/wsmv/receive_response_reader.rb:73:in `with_output'
   7: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/psrp/receive_response_reader.rb:59:in `block in read_output'
   6: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/psrp/receive_response_reader.rb:39:in `read_message'
   5: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/wsmv/receive_response_reader.rb:61:in `read_response'
   4: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/wsmv/receive_response_reader.rb:93:in `send_get_output_message'
   3: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/http/transport.rb:186:in `send_request'
   2: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/http/response_handler.rb:34:in `parse_to_xml'
   1: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/http/response_handler.rb:52:in `raise_if_error'
/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/http/response_handler.rb:73:in `raise_if_wsman_fault': [WSMAN ERROR CODE: 995]: <f:WSManFault Code='995' Machine='1.2.3.4' xmlns:f='http://schemas.microsoft.com/wbem/wsman/1/wsmanfault'><f:Message>The I/O operation has been aborted because of either a thread exit or an application request. </f:Message></f:WSManFault> (WinRM::WinRMWSManFault)
```

Sleep command:
```
# bolt command run 'sleep 50' --modulepath /opt/encore/puppet/ --targets winrm://1.2.3.4:5986 --user testuser --password testpassword --no-ssl-verify --connect-timeout 120
Fact file /etc/facter/facts.d/encore.json was parsed but returned an empty data set
Started on winrm://1.2.3.4:5986...
#<Thread:0x0000000004d8e9c0@/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:471 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
  14: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
  13: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.16.0/lib/bolt/transport/winrm/connection.rb:114:in `block in execute'
  12: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/shells/base.rb:79:in `run'
  11: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/shells/base.rb:131:in `with_command_shell'
  10: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/shells/base.rb:80:in `block in run'
   9: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/psrp/receive_response_reader.rb:58:in `read_output'
   8: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/wsmv/receive_response_reader.rb:73:in `with_output'
   7: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/psrp/receive_response_reader.rb:59:in `block in read_output'
   6: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/psrp/receive_response_reader.rb:39:in `read_message'
   5: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/wsmv/receive_response_reader.rb:61:in `read_response'
   4: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/wsmv/receive_response_reader.rb:93:in `send_get_output_message'
   3: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/http/transport.rb:186:in `send_request'
   2: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/http/response_handler.rb:34:in `parse_to_xml'
   1: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/http/response_handler.rb:52:in `raise_if_error'
/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/http/response_handler.rb:73:in `raise_if_wsman_fault': [WSMAN ERROR CODE: 995]: <f:WSManFault Code='995' Machine='1.2.3.4' xmlns:f='http://schemas.microsoft.com/wbem/wsman/1/wsmanfault'><f:Message>The I/O operation has been aborted because of either a thread exit or an application request. </f:Message></f:WSManFault> (WinRM::WinRMWSManFault)
```

Service Restart Task:
```
# bolt task run --modulepath /opt/encore/puppet/ --targets winrm://1.2.3.4:5986 --user testuser --password testpassword --no-ssl-verify service action='restart' name='WinRM' force='true'
Fact file /etc/facter/facts.d/encore.json was parsed but returned an empty data set
Started on winrm://1.2.3.4:5986...
#<Thread:0x00007f6c68993870@/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:471 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
  14: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
  13: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.16.0/lib/bolt/transport/winrm/connection.rb:114:in `block in execute'
  12: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/shells/base.rb:79:in `run'
  11: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/shells/base.rb:131:in `with_command_shell'
  10: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/shells/base.rb:80:in `block in run'
   9: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/psrp/receive_response_reader.rb:58:in `read_output'
   8: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/wsmv/receive_response_reader.rb:73:in `with_output'
   7: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/psrp/receive_response_reader.rb:59:in `block in read_output'
   6: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/psrp/receive_response_reader.rb:39:in `read_message'
   5: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/wsmv/receive_response_reader.rb:61:in `read_response'
   4: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/wsmv/receive_response_reader.rb:93:in `send_get_output_message'
   3: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/http/transport.rb:186:in `send_request'
   2: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/http/response_handler.rb:34:in `parse_to_xml'
   1: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/http/response_handler.rb:52:in `raise_if_error'
/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/http/response_handler.rb:73:in `raise_if_wsman_fault': [WSMAN ERROR CODE: 995]: <f:WSManFault Code='995' Machine='1.2.3.4' xmlns:f='http://schemas.microsoft.com/wbem/wsman/1/wsmanfault'><f:Message>The I/O operation has been aborted because of either a thread exit or an application request. </f:Message></f:WSManFault> (WinRM::WinRMWSManFault)
```

## Environment
```
# bolt --version
2.16.0

# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.8 (Maipo)
```

**Comment by beechtom** [comment]
Closed by #2030
