### ISSUE TITLE
An lxc/lxd transport

### ISSUE THREAD

**Issue by dontlaugh** [puppetlabs/bolt#2311]
## Use Case
LXD containers require configuration management. They are so-called "system containers", where the philosophy is closer to VMs, but with all the lightweight-ness and speed of linux containers.

They need config management precisely because they are meant to be configured with scripts, cloud-init, etc.

## Describe the Solution You Would Like
I would like to treat each of my LXD containers as a Bolt named **target**, and run commands, tasks, and plans inside them, just like i can do with virtual machine targets.

## Describe Alternatives You've Considered
It's possible to ssh into individual containers, but this requires additional network configuration.

It would also be easy to use the "localhost" target in my bolt plans to wrap local invocations of the `lxc` tool, but this wouldn't give me the nice inventory features.

## Additional Context
I believe that an lxd transport for bolt can be accomplished by wrapping the `lxc` command.

#### lxc list
For example: `lxc list [remote:][container] --format json` - this can tell us if a target is "running", e.g. if the named container is online. Without `--format json`, the output looks like this. 

```
❯ lxc list gf:              
+---------+---------+----------------------+------+-----------+-----------+----------+
|  NAME   |  STATE  |         IPV4         | IPV6 |   TYPE    | SNAPSHOTS | LOCATION |
+---------+---------+----------------------+------+-----------+-----------+----------+
| gitea   | RUNNING | 250.0.132.151 (eth0) |      | CONTAINER | 0         | merc     |
+---------+---------+----------------------+------+-----------+-----------+----------+
| nats    | RUNNING | 250.0.127.87 (eth0)  |      | CONTAINER | 0         | breakout |
+---------+---------+----------------------+------+-----------+-----------+----------+
| vault   | RUNNING | 250.0.138.227 (eth0) |      | CONTAINER | 0         | merc     |
+---------+---------+----------------------+------+-----------+-----------+----------+
```
Note that the IP addresses will _probably_ not be routable from where bolt is run. But that's totally fine because we have...

#### lxc exec

This is akin to `docker exec` and invokes a process inside the container. Given the nature of lxd, there is a _very_ good chance that, at least, a root user and a shell will be available to this command. Here is the help for this command, so you get the idea

```
lxc exec --help
Description:
  Execute commands in instances

  The command is executed directly using exec, so there is no shell and
  shell patterns (variables, file redirects, ...) won't be understood.
  If you need a shell environment you need to execute the shell
  executable, passing the shell commands as arguments, for example:

    lxc exec <instance> -- sh -c "cd /tmp && pwd"

  Mode defaults to non-interactive, interactive mode is selected if both stdin AND stdout are terminals (stderr is ignored).

Usage:
  lxc exec [<remote>:]<instance> [flags] [--] <command line>

Flags:
      --cwd                    Directory to run the command in (default /root)
  -n, --disable-stdin          Disable stdin (reads from /dev/null)
      --env                    Environment variable to set (e.g. HOME=/home/foo)
  -t, --force-interactive      Force pseudo-terminal allocation
  -T, --force-noninteractive   Disable pseudo-terminal allocation
      --group                  Group ID to run the command as (default 0)
      --mode                   Override the terminal mode (auto, interactive or non-interactive) (default "auto")
      --user                   User ID to run the command as (default 0)
```

#### lxc file push/pull

The `file push` and `file pull` subcommands can satisfy the upload and download interfaces. This subcommand is actually quite nice in that it can recursively work with directories, and can set user and group attributes in one go.

The push help. (pull is pretty much the same, but in reverse).
```
lxc file push --help
Description:
  Push files into instances

Usage:
  lxc file push <source path> [<remote>:]<instance>/<path> [[<remote>:]<instance>/<path>...] [flags]

Examples:
  lxc file push /etc/hosts foo/etc/hosts
     To push /etc/hosts into the instance "foo".

Flags:
  -p, --create-dirs   Create any directories necessary
      --gid           Set the file's gid on push (default -1)
      --mode          Set the file's perms on push
  -r, --recursive     Recursively transfer files
      --uid           Set the file's uid on push (default -1)
```

### Configuration

Given what we have available to us via the `lxc` command, we might imagine setting something like this inline in an inventory file

```yaml
targets:
  - name: container1
    uri: "remote1:c1"
    config:
      lxd:
        # if remote is not appropriate for uri, perhaps we specify it in config
        user: 1000 
  - name: container2 
    uri: "remote2:c1"
    config:
      lxd:
        user: 2000
        group: 1000
```

The idea here is that a fully-qualified URI could be mapped to a simple name, in the same way that we can map an IP address to a target name with ssh. (I am actually unclear if this is how a URI could work)

---
Note that there is a ruby library for lxc, but given our use case here I would probably encourage wrapping lxc.

---
Also note: I would encourge using LXD as the name of the transport, since it is the system that allows easy _remote_ use of the lxc container technology. The naming is quite confusing, I'll admit.

**Comment by dontlaugh** [comment]
Regarding configuration, it seems like "uri" isn't correct for this transport. Perhaps it can remain unset for LXD targets.

**Comment by dontlaugh** [comment]
Since testing will almost certainly require vagrant, here is a minimal install

```
❯ vagrant ssh
vagrant@ubuntu2004:~$ sudo apt-get install snapcraft
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  snapcraft
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 7,680 B of archives.
After this operation, 55.3 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 snapcraft all 3.0ubuntu1 [7,680 B]
Fetched 7,680 B in 1s (12.3 kB/s)     
Preconfiguring packages ...
Selecting previously unselected package snapcraft.
(Reading database ... 110747 files and directories currently installed.)
Preparing to unpack .../snapcraft_3.0ubuntu1_all.deb ...
=> Installing the Snapcraft snap
==> Checking connectivity with the snap store
==> Installing the Snapcraft snap for ubuntu-20.04
2020-11-11T00:43:03Z INFO Waiting for automatic snapd restart...
snapcraft 4.3 from Canonical✓ installed
=> Snap installation complete
Unpacking snapcraft (3.0ubuntu1) ...
Setting up snapcraft (3.0ubuntu1) ...
vagrant@ubuntu2004:~$ sntal   ^C
vagrant@ubuntu2004:~$ snap install lxd
error: access denied (try with sudo)
vagrant@ubuntu2004:~$ sudo !!
sudo snap install lxd
lxd 4.7 from Canonical✓ installed
vagrant@ubuntu2004:~$ lxd init
Would you like to use LXD clustering? (yes/no) [default=no]: ^C
vagrant@ubuntu2004:~$ lxd init
Would you like to use LXD clustering? (yes/no) [default=no]: no
Do you want to configure a new storage pool? (yes/no) [default=yes]: 
Name of the new storage pool [default=default]: 
Name of the storage backend to use (lvm, ceph, btrfs, dir) [default=btrfs]: 
Create a new BTRFS pool? (yes/no) [default=yes]: 
Would you like to use an existing empty block device (e.g. a disk or partition)? (yes/no) [default=no]: 
Size in GB of the new loop device (1GB minimum) [default=24GB]: 
Would you like to connect to a MAAS server? (yes/no) [default=no]: 
Would you like to create a new local network bridge? (yes/no) [default=yes]: 
What should the new bridge be called? [default=lxdbr0]: 
What IPv4 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]: 
What IPv6 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]: 
Would you like LXD to be available over the network? (yes/no) [default=no]: 
Would you like stale cached images to be updated automatically? (yes/no) [default=yes] 
Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]: yes
config: {}
networks:
- config:
    ipv4.address: auto
    ipv6.address: auto
  description: ""
  name: lxdbr0
  type: ""
  project: default
storage_pools:
- config:
    size: 24GB
  description: ""
  name: default
  driver: btrfs
profiles:
- config: {}
  description: ""
  devices:
    eth0:
      name: eth0
      network: lxdbr0
      type: nic
    root:
      path: /
      pool: default
      type: disk
  name: default
cluster: null
```

Still need to work out a script to do this in an unattended fashion.

**Comment by dontlaugh** [comment]
This seems to work for an unattended install. We pipe the yaml preseed file to `lxd init`

```ruby
lxd_provision = <<SCRIPT
apt-get install snapcraft -y
snap install lxd
echo 'config: {}
networks:
- config:
    ipv4.address: auto
    ipv6.address: auto
  description: ""
  name: lxdbr0
  type: ""
  project: default
storage_pools:
- config:
    size: 24GB
  description: ""
  name: default
  driver: btrfs
profiles:
- config: {}
  description: ""
  devices:
    eth0:
      name: eth0
      network: lxdbr0
      type: nic
    root:
      path: /
      pool: default
      type: disk
  name: default
cluster: null' | lxd init --preseed
SCRIPT
```

**Comment by dontlaugh** [comment]
I am wondering how we might support two operating modes:

1. `lxc` runs on the bolt controller
2. `lxc` is run on a "proxy" target. For instance, lxc commands are run on a remote machine over ssh.

For `bolt command run`, supporting this seems possible, perhaps straightforward. For uploading files, however, I wonder what kind of behavior we'd expect.

**Comment by dontlaugh** [comment]
Current status of this: I have a rough prototype of remote execution, and file and pull.

Still TODO (incomplete):
* more transport config attributes. `lxc exec` allows setting user/group just like ssh does
* general code cleanup
* integration tests

Regarding tests, this is where I need to focus next. We will need Vagrant. In my WIP pr, I have added a provisioning script that will set up LXD in an Ubuntu VM. This means the lxd daemon is running inside the VM, and containers will be spawned inside the VM.

From here, we can proceed 1 of 2 ways:

1. We can run (via the bolt wrapper I am writing) the `lxc` command line tool on the bolt controller. This has the downside that the tool will need to be installed somehow. It's available in brew, fortunately, and via snap on linux, but it's another thing to install.
2. We can run `lxc` from the command line inside the VM. This is preferable. Is this how the integration tests for ssh run right now? 

Regarding the Vagrant tests generally, I have been getting a lot of failures across the board, but perhaps I have a misconfigured local env.

**Comment by dontlaugh** [comment]
Some good info is available to `lxc info $INSTANCE`

```
Name: container1
Location: lxd-infra-02
Remote: https://10.3.84.1:8443
Architecture: x86_64
Created: 2020/12/24 01:17 UTC
Status: Running
Type: container
Profiles: default
Pid: 10049
Ips:
  eth0:	inet	240.80.229.101	veth12aeea7d
  eth0:	inet6	fe80::216:3eff:fe53:dfc2	veth12aeea7d
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Processes: 26
  CPU usage:
    CPU usage (in seconds): 129
  Memory usage:
    Memory (current): 477.02MB
    Memory (peak): 500.78MB
  Network usage:
    eth0:
      Bytes received: 145.12MB
      Bytes sent: 874.80kB
      Packets received: 13739
      Packets sent: 11911
    lo:
      Bytes received: 356.65kB
      Bytes sent: 356.65kB
      Packets received: 5652
      Packets sent: 5652
```

In particular, it would be useful to expose interfaces/ips, since this will often need to be extracted from one container and configured on another. Is this what facts are for?

**Comment by dontlaugh** [comment]
A few questions:

I get this warning when setting a new config option "remote" on groups.

```
Unknown option 'remote' at 'groups.2.config.lxd' at /home/coleman/Code/infra/bolt/inventory.yaml.
```
How do I fix this properly? [Here is my config class](https://github.com/dontlaugh/bolt/blob/2311_lxd_transport/lib/bolt/config/transport/lxd.rb)

Also, I see this on every task:

```
Skipping cleanup of tmpdir '/tmp/5a881469-0624-41b8-a462-a252f256abd3'
```

Clean seems like something I should do. How do I automatically clean up? 

Finally, I got a strange error

```
<Encoding::UndefinedConversionError> "\xE2" from ASCII-8BIT to UTF-8
```
This might be because I ran bolt against a fresh arch linux container, and it's just **locales** being weird. I'm not sure. In any case, any advice on coding defensively for this would be appreciated. I've never seen it before and I've been hacking on and off on this for a couple of months.


<summary> Logs </summary>

<details>

```
❯ bolt plan run consul::install -t consul                   
Unknown option 'remote' at 'groups.2.config.lxd' at /home/coleman/Code/infra/bolt/inventory.yaml.
Unknown option 'remote' at 'groups.3.config.lxd' at /home/coleman/Code/infra/bolt/inventory.yaml.
Starting: plan consul::install
Starting: task utils::installed_version on consul-01, consul-02, consul-03
Skipping cleanup of tmpdir '/tmp/262ed215-dc2c-467c-87c2-27147608600e'
Skipping cleanup of tmpdir '/tmp/72586291-1191-4816-8899-06e2bcc57f2f'
Skipping cleanup of tmpdir '/tmp/bc5e3265-ac47-4a40-85fb-9c0aec148447'
Finished: task utils::installed_version with 0 failures in 18.29 sec
Starting: task consul::install on consul-01, consul-02, consul-03
Skipping cleanup of tmpdir '/tmp/3d6ef1e7-6905-466f-86ac-9ebb7ae3df25'
Skipping cleanup of tmpdir '/tmp/631751df-7172-4e7c-b114-1896810ffc9b'
Skipping cleanup of tmpdir '/tmp/c2159a6c-b2ca-45ea-9003-99e8d66cffeb'
Finished: task consul::install with 0 failures in 21.07 sec
Starting: task utils::user on consul-01, consul-02, consul-03
Skipping cleanup of tmpdir '/tmp/6a0eaafb-b5b3-4c34-bda7-94e8bf0c432e'
Skipping cleanup of tmpdir '/tmp/858a66a5-3fd2-46db-872c-6ca5951d8a1e'
Skipping cleanup of tmpdir '/tmp/84d927cb-3e74-4943-828b-88212ecf6fb3'
Finished: task utils::user with 0 failures in 19.95 sec
Starting: file upload from /home/coleman/Code/infra/bolt/modules/consul/files/consul.service to /etc/systemd/system/consul.service on consul-01, consul-02, consul-03
Finished: file upload from /home/coleman/Code/infra/bolt/modules/consul/files/consul.service to /etc/systemd/system/consul.service with 0 failures in 1.49 sec
Starting: task utils::mkdir on consul-01, consul-02, consul-03
Skipping cleanup of tmpdir '/tmp/5a881469-0624-41b8-a462-a252f256abd3'
Skipping cleanup of tmpdir '/tmp/3980c258-c186-431a-954a-c76c89a40b6b'
Skipping cleanup of tmpdir '/tmp/ba736cb2-b148-4514-9b04-4750938eb5a8'
Finished: task utils::mkdir with 0 failures in 19.66 sec
Starting: file upload from /home/coleman/Code/infra/bolt/modules/consul/files/agent_config.json to /opt/consul/agent_config.json on consul-01, consul-02, consul-03
Finished: file upload from /home/coleman/Code/infra/bolt/modules/consul/files/agent_config.json to /opt/consul/agent_config.json with 0 failures in 1.46 sec
Starting: task utils::chown on consul-01, consul-02, consul-03
Skipping cleanup of tmpdir '/tmp/1bfc41bb-ddf1-4623-8efc-ed6538075987'
Skipping cleanup of tmpdir '/tmp/18ea24d7-5fb3-449a-936e-f74c2b3e8195'
Skipping cleanup of tmpdir '/tmp/262c8134-151b-4886-af58-bfe925754ff2'
Finished: task utils::chown with 0 failures in 16.85 sec
Starting: task consul::bind_addr_file on consul-01, consul-02, consul-03
Skipping cleanup of tmpdir '/tmp/de2bdd3d-a9b1-4b1f-8ddd-0773f82e5b86'
Skipping cleanup of tmpdir '/tmp/99cb78d1-9b01-4ae3-b19b-e540aae7f41f'
Skipping cleanup of tmpdir '/tmp/8582395c-407c-426c-a07a-6db31b0727f8'
Finished: task consul::bind_addr_file with 0 failures in 18.26 sec
Starting: task utils::chown on consul-01, consul-02, consul-03
Skipping cleanup of tmpdir '/tmp/e42d7c0d-7c43-4961-b165-3ec208d90a36'
Skipping cleanup of tmpdir '/tmp/d30d4e61-43fb-4831-b0a4-d27881e6792d'
Skipping cleanup of tmpdir '/tmp/8b79cc12-748b-4992-8b29-707873828323'
Finished: task utils::chown with 0 failures in 19.99 sec
Starting: command 'systemctl enable consul' on consul-01, consul-02, consul-03
<Encoding::UndefinedConversionError> "\xE2" from ASCII-8BIT to UTF-8
	/home/coleman/Code/bolt/lib/bolt/result.rb:183:in `to_json'
	/home/coleman/Code/bolt/lib/bolt/result.rb:183:in `to_json'
	/home/coleman/Code/bolt/lib/bolt/executor.rb:263:in `with_node_logging'
	/home/coleman/Code/bolt/lib/bolt/executor.rb:273:in `block (2 levels) in run_command'
	/home/coleman/Code/bolt/lib/bolt/executor.rb:141:in `block (3 levels) in queue_execute'
	/home/coleman/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:363:in `run_task'
	/home/coleman/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `block (3 levels) in create_worker'
	/home/coleman/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `loop'
	/home/coleman/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `block (2 levels) in create_worker'
	/home/coleman/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `catch'
	/home/coleman/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block in create_worker'
	/home/coleman/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
<Encoding::UndefinedConversionError> "\xE2" from ASCII-8BIT to UTF-8
	/home/coleman/Code/bolt/lib/bolt/result.rb:183:in `to_json'
	/home/coleman/Code/bolt/lib/bolt/result.rb:183:in `to_json'
	/home/coleman/Code/bolt/lib/bolt/executor.rb:263:in `with_node_logging'
	/home/coleman/Code/bolt/lib/bolt/executor.rb:273:in `block (2 levels) in run_command'
	/home/coleman/Code/bolt/lib/bolt/executor.rb:141:in `block (3 levels) in queue_execute'
	/home/coleman/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:363:in `run_task'
	/home/coleman/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `block (3 levels) in create_worker'
	/home/coleman/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `loop'
	/home/coleman/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `block (2 levels) in create_worker'
	/home/coleman/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `catch'
	/home/coleman/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block in create_worker'
	/home/coleman/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
<Encoding::UndefinedConversionError> "\xE2" from ASCII-8BIT to UTF-8
	/home/coleman/Code/bolt/lib/bolt/result.rb:183:in `to_json'
	/home/coleman/Code/bolt/lib/bolt/result.rb:183:in `to_json'
	/home/coleman/Code/bolt/lib/bolt/executor.rb:263:in `with_node_logging'
	/home/coleman/Code/bolt/lib/bolt/executor.rb:273:in `block (2 levels) in run_command'
	/home/coleman/Code/bolt/lib/bolt/executor.rb:141:in `block (3 levels) in queue_execute'
	/home/coleman/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:363:in `run_task'
	/home/coleman/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `block (3 levels) in create_worker'
	/home/coleman/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `loop'
	/home/coleman/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `block (2 levels) in create_worker'
	/home/coleman/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `catch'
	/home/coleman/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block in create_worker'
	/home/coleman/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
Finished: command 'systemctl enable consul' with 3 failures in 5.75 sec
Finished: plan consul::install in 2 min, 23 sec
Failed on consul-01:
  "\xE2" from ASCII-8BIT to UTF-8
Failed on consul-02:
  "\xE2" from ASCII-8BIT to UTF-8
Failed on consul-03:
  "\xE2" from ASCII-8BIT to UTF-8
Failed on 3 targets: consul-01,consul-02,consul-03
Ran on 3 targets
```

</details>

**Comment by dontlaugh** [comment]
@lucywyman Advice on how I might get rid of the warnings and clean up the temp dirs?

**Comment by lucywyman** [comment]
Hey @dontlaugh I'm so sorry it's taken so long to get back to you!

I put up a small diff of what you'll want to add to get `remote` config option working https://github.com/dontlaugh/bolt/compare/2311_lxd_transport...lucywyman:2311_lxd_transport - our config is definitely a little complicated!

The "Skipping cleanup of tmpdir" comes from the [cleanup config option](https://puppet.com/docs/bolt/latest/bolt_transports_reference.html#cleanup-2) being set to false for a particular target. It should default to true for all the transports that support it, so I suspect it's being set somewhere...you might try `bolt inventory show --detail -t <target_subset>` to see if that config shows up at all?

I'll dig into ASCII error, not sure off the top of my head but wanted to make sure I got back to you!

Lastly, I've been doing some work refactoring the Docker transport that I think might relevant to you, which will make it work the same way our other transports do by using the Shell classes to execute commands and manage pipes. I know you've been working hard on this, and we're 100% fine with merging it as it is now (structurally at least) and then doing a similar refactor later. But just wanted to give you a heads as that refactor will definitely simplify a lot of things! I also didn't want you to see us update your classes in a few months and wonder what was happening. Happy to provide more details if you're interested. 

Thanks so much for doing so much work on this!!

**Comment by dontlaugh** [comment]
Thanks for the tips! They worked swimmingly.

I took a look at #2563 and I think I could accommodate that design. I think it makes sense because I did copy most of the class that inherited from `Base` directly from the docker transport.

**Comment by dontlaugh** [comment]
Okay I have started refactoring towards the `Simple` style you linked to. I have definitely broken something. For instance, when I try to do either of these on an lxd target (a consul-02 containr):

```
bolt command run -t consul-02 'uptime'
bolt file upload -t consul-03 foo /tmp/foo
```
 I get

```
Failed on consul-02:
  undefined method `close' for "":String
  Did you mean?  clone
Failed on 1 target: consul-02
```
I'm not seeting this in my code. Is that from the `Connection`?

I've just started trying to refactor so maybe i just need to poke at it more. It does not seem too different from the docker scenario, and it will be less code in the long run.

My new branch: 
https://github.com/dontlaugh/bolt/blob/2311_lxd_transport_refactor/lib/bolt/transport/lxd/connection.rb
https://github.com/dontlaugh/bolt/blob/2311_lxd_transport_refactor/lib/bolt/transport/lxd.rb
https://github.com/dontlaugh/bolt/blob/2311_lxd_transport_refactor/lib/bolt/config/transport/lxd.rb

**Comment by lucywyman** [comment]
Woohoo! Ok, I opened up a new PR based on your '2311_lxd_transport_refactor' branch. It includes all your commits, I just squashed them down to one commit and gave a more descriptive commit message (though my message can definitely be improved).

The issue with `close` is that the Shell class expected to receive pipes from `Open3.popen3`, which it then manages, as opposed to just getting the strings from `Open3.capture3`. Definitely easy to miss the one-word difference there!

I've still got some cleanup to do on https://github.com/puppetlabs/bolt/pull/2648 but if you want to try it out and make sure it works for your use case that'd be hugely helpful.

Sorry this took so long, but I think we're in the home stretch now!

**Comment by dontlaugh** [comment]
Nice! Thanks so much for squashing that down. That was looking a bit gnarly, especially after all the progress in the project in the past two months.

I will test your branch shortly.

**Comment by dontlaugh** [comment]
Test remote execution: seems to work just fine.

File upload kind of works, but there are some patch suggestions I added to your PR. Even after those, the destination path becomes a directory in a way I wouldn't expect

If I run this upload command against a group **consul**, the resulting `/opt/test.txt` is a directory.

```
bolt file upload test.txt /opt -t consul
```
<details>
<summary>Logs</summary>

```
infra/bolt on  lxd_testing [$!?] on ☁  (us-east-1) took 4s 
❯ bolt file upload test.txt /opt -t consul --log-level debug
Analytics opt-out is set, analytics will be disabled
Loaded project from '/home/coleman/Code/infra/bolt'
Loading modules from /home/coleman/Code/bolt/bolt-modules:/home/coleman/Code/infra/bolt/modules:/home/coleman/Code/infra/bolt/.modules:/home/coleman/Code/bolt/modules
Loaded inventory from /home/coleman/Code/infra/bolt/inventory.yaml
Started with 100 max thread(s)
Starting: file upload from test.txt to /opt on consul-01, consul-02, consul-03
Uploading file test.txt to /opt on ["consul-01"]
Uploading file test.txt to /opt on ["consul-02"]
Uploading file test.txt to /opt on ["consul-03"]
Uploading: 'test.txt' to /opt on consul-01
Uploading: 'test.txt' to /opt on consul-02
Started on consul-01...
Started on consul-02...
Uploading: 'test.txt' to /opt on consul-03
Started on consul-03...
COMMAND OMG ["file", "push", "--recursive", "--create-dirs", "test.txt", "gf:consul-02/tmp/a23e524c-4f3c-4f61-98aa-966d9744a505/test.txt"]
COMMAND OMG ["file", "push", "--recursive", "--create-dirs", "test.txt", "gf:consul-03/tmp/c6c8a873-6bb2-448a-8a93-8873407938b6/test.txt"]
COMMAND OMG ["file", "push", "--recursive", "--create-dirs", "test.txt", "gf:consul-01/tmp/61f93427-4360-4d43-93fc-bf123cc64970/test.txt"]
{"target":"consul-02","action":"upload","object":"test.txt","status":"success","value":{"_output":"Uploaded 'test.txt' to 'consul-02:/opt'"}}
Finished on consul-02:
  Uploaded 'test.txt' to 'consul-02:/opt'
{"target":"consul-01","action":"upload","object":"test.txt","status":"success","value":{"_output":"Uploaded 'test.txt' to 'consul-01:/opt'"}}
Finished on consul-01:
  Uploaded 'test.txt' to 'consul-01:/opt'
{"target":"consul-03","action":"upload","object":"test.txt","status":"success","value":{"_output":"Uploaded 'test.txt' to 'consul-03:/opt'"}}
Finished on consul-03:
  Uploaded 'test.txt' to 'consul-03:/opt'
Finished: file upload from test.txt to /opt with 0 failures in 11.75 sec
Successful on 3 targets: consul-01,consul-02,consul-03
Ran on 3 targets in 11.75 sec

infra/bolt on  lxd_testing [$!?] on ☁  (us-east-1) took 12s 
❯ bolt command run 'cat /opt/test.txt' -t consul
Started on consul-01...
Started on consul-03...
Started on consul-02...
Failed on consul-02:
  The command failed with exit code 1
  STDERR:
    cat: /opt/test.txt: Is a directory
Failed on consul-01:
  The command failed with exit code 1
  STDERR:
    cat: /opt/test.txt: Is a directory
Failed on consul-03:
  The command failed with exit code 1
  STDERR:
    cat: /opt/test.txt: Is a directory
Failed on 3 targets: consul-01,consul-02,consul-03
Ran on 3 targets in 2.88 sec
```

</details>

I think I initially wrote this without any of the upload-to-temp-and-then-move machinery, but now it needs to be made to work in the manner of the other transports.
