### ISSUE TITLE
Improve error messaging for "bolt script run" on Powershell

### ISSUE THREAD

**Issue by jpogran** [puppetlabs/bolt#2659]
## Describe the Bug

When the PowerShell `ExecutionPolicy` is set to `Restricted` or `AllSigned`, Bolt won’t be able to execute an unsigned powershell script via bolt script run. 

## Expected Behavior

A clear generic error returned to the user or an error that explains the restricted execution policy that is preventing Bolt from running.

## Steps to Reproduce
1. Create a Windows target with the PowerShell Execution Policy set to `Restricted` or `AllSigned`
2. Execute a powershell script on target

## Environment
 - Version 3.0.0
 - Platform Windows

## Additional Context

Example output:

```
Started on winrm://wsus.dreamworx.nl...
--
Failed on winrm://wsus.dreamworx.nl:
The command failed with exit code 1
STDERR:
$invokeArgs = @{
: System.Management.Automation.ParameterBindingValidationException: Cannot validate argument on parameter 'ScriptBlock'. The argument is null. Provide a valid value for the argument, and then try running the command again. ---> System.Management.Automation.ValidationMetadataException: The argument is null. Provide a valid value for the argument, and then try running the command again.
at System.Management.Automation.ValidateNotNullAttribute.Validate(Object arguments, EngineIntrinsics engineIntrinsics)
at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
--- End of inner exception stack trace ---
at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException
Failed on 1 target: winrm://wsus.dreamworx.nl
Ran on 1 target in 2.09 sec
```

Reported by : @kreeuwijk

**Comment by jpogran** [comment]
Note that Bolt ships it's PowerShell module signed, so this problem occurs on the target not the host running Bolt.

We can improve the error message by either checking for execution policy first before executing the script and returning a custom message, or by executing the script in a try/catch block and relying on the error message to be coherent.
