### ISSUE TITLE
Invoke-BoltCommand fails when passing multiple servers to -Targets

### ISSUE THREAD

**Issue by rogfut** [puppetlabs/bolt#2739]
## Describe the Bug
When running an Invoke-BoltCommand and passing in a server list text file that is UTF8 encoded with .txt extension, the command throws 800+ line Traceback

`Invoke-BoltCommand -Command "write-host 'hi'" -Targets '@servers.txt' -Transport winrm -Ssl:$false -User roger@example.com -PasswordPrompt`

This also happens when I pass in a comma delimited server list as a string:

`Invoke-BoltCommand -Command "write-host 'hi'" -Targets 'server01.example.com,server02.example.com' -Transport winrm -Ssl:$false -User roger@example.com -PasswordPrompt`

## Expected Behavior
The bolt command should be successful and output the following:
```Started on <server>...
Finished on <server>:
  hi
```

When I run the command and pass a single server to -Targets, the command is successful. 

``Invoke-BoltCommand -Command "write-host 'hi'" -Targets 'server01.example.com' -Transport winrm -Ssl:$false -User roger@example.com -PasswordPrompt`

## Steps to Reproduce
`Invoke-BoltCommand -Command "write-host 'hi'" -Targets '@servers.txt' -Transport winrm -Ssl:$false -User roger@example.com -PasswordPrompt`

where @'servers.txt' m has 12+ servers, is in my cwd, is UTF8 encoded with CRLF end of line sequence

## Environment
 - Version 3.4.0
 - Platform Windows 10 Enterprise 10.0.17763
 - Powershell version
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17763  1490

## Additional Context
Stdout from the command is attached
[puppet_error_log.txt](https://github.com/puppetlabs/bolt/files/6202051/puppet_error_log.txt)

**Comment by lucywyman** [comment]
Ah, that's a duplicate of this issue: https://github.com/puppetlabs/bolt/issues/1478
We spent a few days investigating the issue when it first happened, but it only happens very rarely and we couldn't pinpoint what the actual issue is. Previously we had only seen this on MacOS though, so running into it on Windows is a very interesting new data point! Just for a little more data to help us diagnose the issue, how did you install Bolt?

Re-installing (through whatever method you originally installed it) should do the trick, and to be extra sure you can remove `C:\Program Files\Puppet Labs\Bolt` first and then reinstall. Let us know if that doesn't work and we'll help get you sorted!

**Comment by rogfut** [comment]
Hi Lucy, I installed bolt using the Windows MSI.  I had a previous bolt installed via MSI (2.7 or something? not sure!).

I'll go ahead and uninstall => clean `C:\Program Files\Puppet Labs\Bolt` => install via msi again.  Will let you know how it goes.

**Comment by rogfut** [comment]
I uninstalled bolt via uninstaller, uninstalled PDK via uninstaller, reinstalled bolt 3.4.0 via msi and now I get a different trace.  I have not yet reinstalled the PDK but I dont think there is any dependency there from Bolt.

```
PS C:\Users\roger.futrell\Documents\code\bolt> Invoke-BoltCommand -Command "Write-Host 'Hi'" -Targets $servers -User roger.example.com -Ssl:$false -PasswordPrompt
Please enter your password:
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in `<class:GssOID>' will be disallowed in ffi-2.0.
C:/Program Files/Puppet Labs/Bolt/lib/ruby/gems/2.7.0/gems/bolt-3.4.0/lib/bolt/transport/ssh.rb:34: warning: Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead
Started on server.example.com...
Failed on server.example.com:
  Timeout after 10 seconds connecting to server.example.com
Failed on 12 targets:
Ran on 12 targets in 15.33 sec
```

**Comment by beechtom** [comment]
@rogfut Those deprecation warnings are from the gssapi gem, which is one of Bolt's dependencies. We have a ticket up to fix it, which you can track here: https://github.com/zenchild/gssapi/pull/35 .

**Comment by rogfut** [comment]
@lucywyman reinstall seemed to have done the trick, feel free to close if this is a duplicate

Hi @beechtom if you are referring to the deleted comment I forgot to set the -Transport to winrm 🤦‍♂️ Thanks for the link to the PR I've subscribed to it
