### ISSUE TITLE
Error + traceback using run_as with script step in a YAML plan

### ISSUE THREAD

**Issue by hestonhoffman** [puppetlabs/bolt#2765]
## Describe the Bug
I'm getting a weird error with lots of traceback when I try to run a script from a plan with `run_as: root`

## Expected Behavior
I expect the plan to execute the command from the script using root and the `sudo-password`.

## Steps to Reproduce
Here's what I have:
A lightly modified template plan:
```yaml
# homeserver/plans/update.yaml
description: Update apt

parameters:
  targets:
    type: TargetSpec
    description: A list of targets to run actions on
    default: localhost
steps:
  - message: Hello from homeserver::update
  - script: homeserver/update.sh
    targets: $targets
    run_as: root
```
The following (scrubbed) inventory:
```yaml
groups:
- name: home
  targets:
    - alias: homeserver
      uri: 192.168.1.2
  config:
    transport: ssh
    ssh:
      user: homeuser
      private-key: "~/.ssh/id_rsa"
      run-as: root
      sudo-password: hunter2
```
A script with a command that requires sudo:
```bash
#!/bin/bash
# homeserver/files/update.sh

apt-get update
```

Command:
`bolt plan run homeserver::update -t homeserver`

Output:
```
Starting: plan homeserver::update
Hello from homeserver::update
Starting: script /Users/heston.hoffman/bolt-projects/homeserver/files/update.sh on 192.168.1.2
#<Thread:0x00007fe8c220e290 /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:471 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	15: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
	14: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/bolt-3.5.0/lib/bolt/transport/ssh/connection.rb:205:in `block (2 levels) in execute'
	13: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:180:in `loop'
	12: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:180:in `loop'
	11: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:180:in `block in loop'
	10: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:227:in `process'
	 9: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/event_loop.rb:28:in `process'
	 8: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/event_loop.rb:100:in `ev_preprocess'
	 7: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/event_loop.rb:100:in `each'
	 6: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:248:in `ev_preprocess'
	 5: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:548:in `dispatch_incoming_packets'
	 4: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:673:in `channel_extended_data'
	 3: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/channel.rb:598:in `do_extended_data'
	 2: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/bolt-3.5.0/lib/bolt/transport/ssh/connection.rb:191:in `block (4 levels) in execute'
	 1: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/bolt-3.5.0/lib/bolt/transport/ssh/connection.rb:191:in `<<'
/opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/bolt-3.5.0/lib/bolt/transport/ssh/connection.rb:191:in `write': closed stream (IOError)
#<Thread:0x00007fe8c2214b90 /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:471 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	15: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
	14: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/bolt-3.5.0/lib/bolt/transport/ssh/connection.rb:205:in `block (2 levels) in execute'
	13: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:180:in `loop'
	12: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:180:in `loop'
	11: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:180:in `block in loop'
	10: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:227:in `process'
	 9: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/event_loop.rb:28:in `process'
	 8: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/event_loop.rb:100:in `ev_preprocess'
	 7: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/event_loop.rb:100:in `each'
	 6: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:248:in `ev_preprocess'
	 5: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:548:in `dispatch_incoming_packets'
	 4: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:673:in `channel_extended_data'
	 3: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/channel.rb:598:in `do_extended_data'
	 2: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/bolt-3.5.0/lib/bolt/transport/ssh/connection.rb:191:in `block (4 levels) in execute'
	 1: from /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/bolt-3.5.0/lib/bolt/transport/ssh/connection.rb:191:in `<<'
/opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/bolt-3.5.0/lib/bolt/transport/ssh/connection.rb:191:in `write': closed stream (IOError)
Finished: script /Users/heston.hoffman/bolt-projects/homeserver/files/update.sh with 1 failure in 3.76 sec
Finished: plan homeserver::update in 3.77 sec
Failed on 192.168.1.2:
  closed stream
Failed on 1 target: 192.168.1.2
Ran on 1 target
```

## Environment
- Bolt 3.5.0
- MacOS Catalina 10.15.7
- Target is Ubuntu 20.04.1

**Comment by lucywyman** [comment]
Hmm, so what seems to be happening is the command to run the script prints something to STDERR, but when we try to save that to a variable to expose to the user it's saying that the pipe we're trying to write to is closed (the one we create to save the data to). I'm really not sure why our pipe would be closing prematurely, since it should only close once everything has been saved.  When you get a chance can you try running with `--log-level trace` and post a scrubbed version of output, so we can see what the last thing it does successfully is?

**Comment by hestonhoffman** [comment]
I don't have access to this machine today, but I'll take a look tomorrow when I'm back home 👍

**Comment by hestonhoffman** [comment]
I tried this again and I can't reproduce it. Really weird. I'm going to close this ticket.
