### ISSUE TITLE
Bolt is using non-puppet ruby by default on Windows

### ISSUE THREAD

**Issue by Levelleor** [puppetlabs/bolt#3059]
## Describe the Bug
When running a simple bolt manifest on Windows through WinRM looks like it's failing before the manifest even starting. It's trying to use our system ruby `C:/software/ruby24/` by default, even though Puppet Agent comes with an on-board Ruby. And indeed, I removed system Ruby from PATH and Bolt fallbacks to agent's ruby automatically. I can't leave the system without system ruby in PATH, is there a way to strictly define the version Bolt should be using? 

```
Starting: install puppet and gather facts on win11
[win11] out: 5
[win11] out: C:\Users\builduser\AppData\Local\Temp\jeixtomp.su0
[win11] out: Version parameter not defined and agent detected. Nothing to do.
[win11] out: 5
[win11] out: C:\Users\builduser\AppData\Local\Temp\hkuemzwt.vge
[win11] err: ruby.exe : C:/software/ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- puppet (LoadError)
[win11] err:     + CategoryInfo          : NotSpecified: (C:/software/ruby24...pet (LoadError):String) [], RemoteException
[win11] err:     + FullyQualifiedErrorId : NativeCommandError
[win11] err:    from C:/software/ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require' from C:/Users/builduser/AppData/Local/Temp/hkuemzwt.vge/custom_facts.rb:5:in `<main>'
Finished: install puppet and gather facts with 1 failure in 22.88 sec
Starting: apply catalog on
Finished: apply catalog with 0 failures in 0.0 sec
Failed on 1 target: win11
```

## Expected Behavior
Bolt should use Puppet Agent's onboard ruby by default.

## Steps to Reproduce
1. Install ruby
2. Make sure it's in the system PATH

## Environment
 - Version 3.21.0
 - Platform Windows 11

**Comment by Levelleor** [comment]
I wasn't installing Bolt on Windows. I assume Bolt operates through Puppet Agent and there is none it tried to install one. So I thought Bolt could be used as a starting point to bootstrap clean Windows machines from scratch, where Bolt will setup everything it needs, including Chocolatey. 

And no, I have not used apply_prep. Though I do not have access to that environment anymore so I won't be able to test this exact issue anymore. 

Though, let me know if I am wrong in assuming the above.
