### ISSUE TITLE
bolt-inventory-pdb: GemNotFoundException

### ISSUE THREAD

**Issue by vdczzz** [puppetlabs/bolt#715]
Running on Mac OS X Mojave `macOS 10.14 (18A391)`, installed via `brew cask install puppetlabs/puppet/puppet-bolt`

```
vdc@ZL-10546 ~ $ bolt
Usage: bolt <subcommand> <action> [options]

Available subcommands:
  bolt command run <command>       Run a command remotely
  bolt file upload <src> <dest>    Upload a local file
  bolt script run <script>         Upload a local script and run it remotely
  bolt task show                   Show list of available tasks
  bolt task show <task>            Show documentation for task
  bolt task run <task> [params]    Run a Puppet task
  bolt plan show                   Show list of available plans
  bolt plan show <plan>            Show details for plan
  bolt plan run <plan> [params]    Run a Puppet task plan
  bolt puppetfile install          Install modules from a Puppetfile into a Boltdir

Run `bolt <subcommand> --help` to view specific examples.

where [options] are:
    -n, --nodes NODES                Identifies the nodes to target.
                                     Enter a comma-separated list of node URIs or group names.
                                     Or read a node list from an input file '@<file>' or stdin '-'.
                                     Example: --nodes localhost,node_group,ssh://nix.com:23,winrm://windows.puppet.com
                                     URI format is [protocol://]host[:port]
                                     SSH is the default protocol; may be ssh, winrm, pcp, local
                                     For Windows nodes, specify the winrm:// protocol if it has not be configured
                                     For SSH, port defaults to `22`
                                     For WinRM, port defaults to `5985` or `5986` based on the --[no-]ssl setting
    -q, --query QUERY                Query PuppetDB to determine the targets
        --noop                       Execute a task that supports it in noop mode
        --description DESCRIPTION    Description to use for the job
        --params PARAMETERS          Parameters to a task or plan as json, a json file '@<file>', or on stdin '-'
Authentication:
    -u, --user USER                  User to authenticate as
    -p, --password [PASSWORD]        Password to authenticate with. Omit the value to prompt for the password.
        --private-key KEY            Private ssh key to authenticate with
        --[no-]host-key-check        Check host keys with SSH
        --[no-]ssl                   Use SSL with WinRM
        --[no-]ssl-verify            Verify remote host SSL certificate with WinRM
Escalation:
        --run-as USER                User to run as using privilege escalation
        --sudo-password [PASSWORD]   Password for privilege escalation. Omit the value to prompt for the password.
Run context:
    -c, --concurrency CONCURRENCY    Maximum number of simultaneous connections (default: 100)
        --compile-concurrency CONCURRENCY
                                     Maximum number of simultaneous manifest block compiles (default: number of cores)
        --modulepath MODULES         List of directories containing modules, separated by ':'
        --boltdir FILEPATH           Specify what Boltdir to load config from (default: autodiscovered from current working dir)
        --configfile FILEPATH        Specify where to load config from (default: ~/.puppetlabs/bolt/bolt.yaml)
        --inventoryfile FILEPATH     Specify where to load inventory from (default: ~/.puppetlabs/bolt/inventory.yaml)
Transports:
        --transport TRANSPORT        Specify a default transport: ssh, winrm, pcp, local
        --connect-timeout TIMEOUT    Connection timeout (defaults vary)
        --[no-]tty                   Request a pseudo TTY on nodes that support it
        --tmpdir DIR                 The directory to upload and execute temporary files on the target
Display:
        --format FORMAT              Output format to use: human or json
        --[no-]color                 Whether to show output in color
    -h, --help                       Display help
        --verbose                    Display verbose logging
        --debug                      Display debug logging
        --trace                      Display error stack traces
        --version                    Display the version
vdc@ZL-10546 ~ $ bolt --version
1.1.0
vdc@ZL-10546 ~ $ bolt-inventory-pdb
Traceback (most recent call last):
	2: from /opt/puppetlabs/bolt/bin/bolt-inventory-pdb:23:in `<main>'
	1: from /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bolt (>= 0.a) with executable bolt-inventory-pdb (Gem::GemNotFoundException)
```

**Comment by donoghuc** [comment]
Bolt is not yet packaged for `macOS 10.14 (18A391)`. We can update the our [Cask](https://github.com/puppetlabs/homebrew-puppet/blob/master/Casks/puppet-bolt.rb) to prevent downloads for 10.14 until we support it. Thanks.

**Comment by vdczzz** [comment]
In the meantime is there a way to install manually? Any timeline on an available package?

**Comment by MikaelSmith** [comment]
Can you try re-installing? That looks really strange, and I've occasionally seen something similar happen when the package doesn't install right.

**Comment by vdczzz** [comment]
```
vdc@ZL-10546 ~ $ brew cask --force uninstall puppet-bolt
==> Uninstalling Cask puppet-bolt
==> Running uninstall process for puppet-bolt; your password may be necessary
==> Uninstalling packages:
com.puppetlabs.puppet-bolt
Password:
==> Purging files for version 1.1.0 of Cask puppet-bolt
vdc@ZL-10546 ~ $ brew cask install puppetlabs/puppet/puppet-bolt
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/cask-versions, homebrew/core and homebrew/cask).
==> Updated Formulae
ffmpeg@2.8                                                                       git-review                                                                       wine

==> Satisfying dependencies
==> Downloading https://downloads.puppet.com/mac/puppet5/10.13/x86_64/puppet-bolt-1.1.0-1.osx10.13.dmg
Already downloaded: /Users/vdc/Library/Caches/Homebrew/downloads/0b89bb163492a2e892312ad09f9387ac25295a52a8e8611979388c8b58a750da--puppet-bolt-1.1.0-1.osx10.13.dmg
==> Verifying SHA-256 checksum for Cask 'puppet-bolt'.
==> Installing Cask puppet-bolt
==> Running installer for puppet-bolt; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
installer: Package name is puppet-bolt
installer: Installing at base path /
installer: The install was successful.
🍺  puppet-bolt was successfully installed!
vdc@ZL-10546 ~ $ bolt --version
1.1.0
vdc@ZL-10546 ~ $ bolt-inventory-pdb
Traceback (most recent call last):
	2: from /opt/puppetlabs/bolt/bin/bolt-inventory-pdb:23:in `<main>'
	1: from /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bolt (>= 0.a) with executable bolt-inventory-pdb (Gem::GemNotFoundException)
```

**Comment by MikaelSmith** [comment]
Ok thanks. I guess I'll upgrade to 10.14 and see what's going on.

I don't think we add `bolt-inventory-pdb` to a location accessible by PATH in packaging (that seems like an oversight). Did you add something to PATH?

**Comment by vdczzz** [comment]
I did add `/opt/puppetlabs/bin:/opt/puppetlabs/bolt/bin` to my PATH, but it didn't change the result to call it directly:

```
vdc@ZL-10546 bin $ ./bolt-inventory-pdb
Traceback (most recent call last):
	2: from ./bolt-inventory-pdb:23:in `<main>'
	1: from /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bolt (>= 0.a) with executable bolt-inventory-pdb (Gem::GemNotFoundException)
```

**Comment by MikaelSmith** [comment]
Does your rvm Ruby possibly have an old version of Bolt in it? I'm on 10.14 and not having any problems with the package.

**Comment by MikaelSmith** [comment]
Also any GEM_* environment variables set?

**Comment by vdczzz** [comment]
Ah! I had this in my `.bash_profile` from a long-forgotten RVM install:
`[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"`

I commented it out and now `bolt-inventory-pdb` works fine. Since `bolt` worked I didn't think to check.

Thanks for the help, and sorry for the noise.
